apiVersion: v1
kind: Template
metadata:
  name: docker-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: testing-yaml  
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: testing-yaml 
    namespace: rinkuk019-dev
    labels:
      app: testing-yaml 
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'testing-yaml:latest'
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
      postCommit: {}
    source:
      type: Git
      git:
        uri: https://github.com/Rinku608/testing-yaml
        ref: master
      contextDir: /
    triggers:
      - type: Generic
        generic:
          secretReference:
            name: testing-yaml-generic-webhook-secret
      - type: GitHub
        github:
          secretReference:
            name: testing-yaml-github-webhook-secret
      - type: ConfigChange
    runPolicy: Serial
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: testing-yaml 
    namespace: rinkuk019-dev
    labels:
      app: testing-yaml 
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - testing-yaml 
          from:
            kind: ImageStreamTag
            namespace: rinkuk019-dev
            name: 'testing-yaml:latest'
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: testing-yaml 
      deploymentconfig: testing-yaml 
    template:
      metadata:
        labels:
          app: testing-yaml 
          deploymentconfig: testing-yaml 
      spec:
        volumes:
          - name: claim1
            persistentVolumeClaim:
              claimName: claim1
        containers:
          - name: testing-yaml 
            resources: {}
            volumeMounts:
              - name: claim1
                mountPath: /var/local/SP            
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
    name: testing-yaml 
    namespace: rinkuk019-dev
    labels:
      app: testing-yaml 
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: testing-yaml 
      deploymentconfig: testing-yaml 
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: testing-yaml 
    namespace: rinkuk019-dev
    labels:
      app: testing-yaml 
    annotations:
  spec:
    to:
      kind: Service
      name: testing-yaml 
      weight: 100
    port:
      targetPort: 8080-tcp
  wildcardPolicy: None
